Traceback (most recent call last):
  File "/Users/ashley/anaconda3/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/Users/ashley/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/ashley/anaconda3/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/ashley/anaconda3/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/ashley/anaconda3/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/Users/ashley/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/Users/ashley/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/ashley/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Import necessary packages
import h5py # version '2.10.0' is needed
import numpy as np
from matplotlib import pyplot as plt
from pynwb import NWBHDF5IO

# read the file 
io = NWBHDF5IO('000006/sub-anm369962/sub-anm369962_ses-20170310.nwb', 'r')
nwb_file = io.read()
print(type(nwb_file))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mUnsupportedOperation[0m                      Traceback (most recent call last)
[0;32m<ipython-input-1-0e2f97dfc04f>[0m in [0;36m<module>[0;34m[0m
[1;32m      6[0m [0;34m[0m[0m
[1;32m      7[0m [0;31m# read the file[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 8[0;31m [0mio[0m [0;34m=[0m [0mNWBHDF5IO[0m[0;34m([0m[0;34m'000006/sub-anm369962/sub-anm369962_ses-20170310.nwb'[0m[0;34m,[0m [0;34m'r'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      9[0m [0mnwb_file[0m [0;34m=[0m [0mio[0m[0;34m.[0m[0mread[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     10[0m [0mprint[0m[0;34m([0m[0mtype[0m[0;34m([0m[0mnwb_file[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/anaconda3/lib/python3.7/site-packages/hdmf/utils.py[0m in [0;36mfunc_call[0;34m(*args, **kwargs)[0m
[1;32m    578[0m             [0;32mdef[0m [0mfunc_call[0m[0;34m([0m[0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    579[0m                 [0mpargs[0m [0;34m=[0m [0m_check_args[0m[0;34m([0m[0margs[0m[0;34m,[0m [0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 580[0;31m                 [0;32mreturn[0m [0mfunc[0m[0;34m([0m[0margs[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m,[0m [0;34m**[0m[0mpargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    581[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    582[0m             [0;32mdef[0m [0mfunc_call[0m[0;34m([0m[0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/anaconda3/lib/python3.7/site-packages/pynwb/__init__.py[0m in [0;36m__init__[0;34m(self, **kwargs)[0m
[1;32m    244[0m             [0;32melif[0m [0mmanager[0m [0;32mis[0m [0;32mNone[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    245[0m                 [0mmanager[0m [0;34m=[0m [0mget_manager[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 246[0;31m         [0msuper[0m[0;34m([0m[0mNWBHDF5IO[0m[0;34m,[0m [0mself[0m[0;34m)[0m[0;34m.[0m[0m__init__[0m[0;34m([0m[0mpath[0m[0;34m,[0m [0mmanager[0m[0;34m=[0m[0mmanager[0m[0;34m,[0m [0mmode[0m[0;34m=[0m[0mmode[0m[0;34m,[0m [0mfile[0m[0;34m=[0m[0mfile_obj[0m[0;34m,[0m [0mcomm[0m[0;34m=[0m[0mcomm[0m[0;34m,[0m [0mdriver[0m[0;34m=[0m[0mdriver[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    247[0m [0;34m[0m[0m
[1;32m    248[0m     @docval({'name': 'src_io', 'type': HDMFIO, 'doc': 'the HDMFIO object for reading the data to export'},

[0;32m~/anaconda3/lib/python3.7/site-packages/hdmf/utils.py[0m in [0;36mfunc_call[0;34m(*args, **kwargs)[0m
[1;32m    578[0m             [0;32mdef[0m [0mfunc_call[0m[0;34m([0m[0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    579[0m                 [0mpargs[0m [0;34m=[0m [0m_check_args[0m[0;34m([0m[0margs[0m[0;34m,[0m [0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 580[0;31m                 [0;32mreturn[0m [0mfunc[0m[0;34m([0m[0margs[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m,[0m [0;34m**[0m[0mpargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    581[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    582[0m             [0;32mdef[0m [0mfunc_call[0m[0;34m([0m[0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/anaconda3/lib/python3.7/site-packages/hdmf/backends/hdf5/h5tools.py[0m in [0;36m__init__[0;34m(self, **kwargs)[0m
[1;32m     60[0m         [0;32mif[0m [0mfile_obj[0m [0;32mis[0m [0;32mNone[0m [0;32mand[0m [0;32mnot[0m [0mos[0m[0;34m.[0m[0mpath[0m[0;34m.[0m[0mexists[0m[0;34m([0m[0mpath[0m[0;34m)[0m [0;32mand[0m [0;34m([0m[0mmode[0m [0;34m==[0m [0;34m'r'[0m [0;32mor[0m [0mmode[0m [0;34m==[0m [0;34m'r+'[0m[0;34m)[0m [0;32mand[0m [0mdriver[0m [0;34m!=[0m [0;34m'ros3'[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m     61[0m             [0mmsg[0m [0;34m=[0m [0;34m"Unable to open file %s in '%s' mode. File does not exist."[0m [0;34m%[0m [0;34m([0m[0mpath[0m[0;34m,[0m [0mmode[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 62[0;31m             [0;32mraise[0m [0mUnsupportedOperation[0m[0;34m([0m[0mmsg[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     63[0m [0;34m[0m[0m
[1;32m     64[0m         [0;32mif[0m [0mfile_obj[0m [0;32mis[0m [0;32mNone[0m [0;32mand[0m [0mos[0m[0;34m.[0m[0mpath[0m[0;34m.[0m[0mexists[0m[0;34m([0m[0mpath[0m[0;34m)[0m [0;32mand[0m [0;34m([0m[0mmode[0m [0;34m==[0m [0;34m'w-'[0m [0;32mor[0m [0mmode[0m [0;34m==[0m [0;34m'x'[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mUnsupportedOperation[0m: Unable to open file 000006/sub-anm369962/sub-anm369962_ses-20170310.nwb in 'r' mode. File does not exist.
UnsupportedOperation: Unable to open file 000006/sub-anm369962/sub-anm369962_ses-20170310.nwb in 'r' mode. File does not exist.

